### ISSUE TITLE
Can you release packages to the npm?

### ISSUE THREAD

**Issue by linonetwo** [DragonBones/DragonBonesJS#104]
Instead of generating locally and copy paste around, I think dependencies should be located in node_modules.

**Comment by taoabc** [comment]
同样希望能使用npm的方式开发，隔离性更强，可能的话，我可以参与开发，但是更改比较大。如果官方没有意愿的话，我就自己更改了，前提是龙骨运行时足够稳定，否则合并官方代码会比较麻烦。

**Comment by taoabc** [comment]
I have released a pure dragonbones runtime library that use npm, which called [libdragonbones](https://github.com/taoabc/libdragonbones). and npm package: [https://www.npmjs.com/package/libdragonbones](https://www.npmjs.com/package/libdragonbones).

I'm also glad to contribute that repo to the DragonBones official organization.

**Comment by akdcl** [comment]
@taoabc 龙骨运行时目前相对比较稳定，也暂时不会添加新的功能，只会修改 bug。

**Comment by linonetwo** [comment]
太好了
