### ISSUE TITLE
Pixi Demo is not working good

### ISSUE THREAD

**Issue by javierlog08** [DragonBones/DragonBonesJS#26]
Im running Pixi demo, but the display is incorrect.

How I can Solve it?

![GitHub Logo](https://lh4.googleusercontent.com/h7SPcc_51yQ2zVGGQQGJP3RiWf7gx1XfI4oaE-bdma_hOw-ISNEkiUO2DOYilQF_Ol8nry_wZ66m4Ho=w1920-h922-rw)

**Comment by akdcl** [comment]
Hi,
it it looks like the old version, try to update the latest version.

**Comment by javierlog08** [comment]
Sorry recently I just clone the project, and build again the project sources and it works fine.

I guess that I was using another older version of dragon bones (dont know how)

Thank you, you can close this bro
