### ISSUE TITLE
pixi.js 4.3.x display error

### ISSUE THREAD

**Issue by shaoahs** [DragonBones/DragonBonesJS#27]
pixi.js 4.3.0        ok!
pixi.js 4.3.1        error!
pixi.js 4.3.2        error!
pixi.js 4.3.3        error!

**Comment by akdcl** [comment]
Hi,
the bug has been fixed :)

**Comment by aboutqx** [comment]
pixi-4.3.0及以上报错，Cannot read property '_updateID' of null

**Comment by akdcl** [comment]
这个错误现在修复了https://github.com/DragonBones/DragonBonesJS/commit/5f5d95eade7eb409eb055c0a03b66e1f90f464a3
