### ISSUE TITLE
BUG: PixiFactory.getTextureDisplay

### ISSUE THREAD

**Issue by bitbay** [DragonBones/DragonBonesJS#29]
The [arguments passed](https://github.com/DragonBones/DragonBonesJS/blob/master/Pixi/src/dragonBones/pixi/PixiFactory.ts#L192) to PIXI.Texture are incorrect.
The second (currently null) definitely should be the rectangle of the sub-texture (aka "frame"), not sure about the following parameters though ("The area of original texture" vs "Trimmed rectangle of original texture").
I get the same (correct) result with both
```
textureData.texture = new PIXI.Texture(
    textureAtlasTexture,
    <PIXI.Rectangle><any>textureData.region,
    null,
    originSize,
    textureData.rotated as any // .d.ts bug
);
```
and
```
textureData.texture = new PIXI.Texture(
    textureAtlasTexture,
    <PIXI.Rectangle><any>textureData.region,
    originSize,
    null,
    textureData.rotated as any // .d.ts bug
);
```
Without submerging into the depths of both libraries, i would go with the second one though, since [pixijs docs](http://pixijs.download/dev/docs/PIXI.Texture.html) name it similar - "orig", "The area of original texture".
I used pixi 4.5.1, but since the constructors signature hasn't changed between previous (3.x) and current version, i would say it shouldn't make a difference which version You use.

**Comment by akdcl** [comment]
Sorry for the later reply, the bug has been fixed. https://github.com/DragonBones/DragonBonesJS/commit/229e5f11b38299c2ef20018b6880f7105a5b8db1

**Comment by bitbay** [comment]
@akdcl thank You, definitely will be a great/must have fix for PIXI clients!
