### ISSUE TITLE
什么时候支持5.3的二进制格式呢？

### ISSUE THREAD

**Issue by puny-d** [DragonBones/DragonBonesJS#31]
看5.3版本新支持二进制格式，性能有大幅度提升，我用的是pixi.js+ db，请问什么时候可以支持呢

**Comment by akdcl** [comment]
pixi 的支持预计稍稍晚一些，预计两周内，我们就会将 github 上的源码更新为最新版本，其中会包含 pixi 的实现和发布。

**Comment by puny-d** [comment]
非常感谢你们的努力，还有就是egret什么时候可以推出js版本呢，现在ts版本很不方便和其他的框架结合，而且接口设计的也不如pixi简洁，但是毕竟egret对db支持更友好，pixi的db。。部分的api只能看源码，官网的文档是egret的

**Comment by puny-d** [comment]
你好，不知道现在是否支持二进制？

**Comment by akdcl** [comment]
pixi 的已经发布

**Comment by puny-d** [comment]
你好，我升级了新的db库，使用二进制时，配合pixi.js 4.4，发现现有的有些龙骨动画发生了改变，主要动作集中在attack和attack-1
[new.zip](https://github.com/DragonBones/DragonBonesJS/files/1175691/new.zip)
[old.zip](https://github.com/DragonBones/DragonBonesJS/files/1175692/old.zip)

**Comment by puny-d** [comment]
....我发现替换二进制文件以后，基本上所有的龙骨显示都或多或少有异常。。。

**Comment by akdcl** [comment]
能指出区别的细节吗？看了一下没太发现细节

**Comment by akdcl** [comment]
找到了，会修复这个 bug

**Comment by puny-d** [comment]
好的，谢谢，还有就是我用了新的lib以后，龙骨的大小相关的和之前的就不一样了，这个只发生在一些特殊的龙骨上，请问一下龙骨的height和width到底是根据什么决定的呢？第一帧的大小，还是什么？

**Comment by puny-d** [comment]
![snip20170726_2](https://user-images.githubusercontent.com/3891276/28614793-93579ee2-7229-11e7-80de-a61340ac4bd5.png)
比如这个地方，火箭是从红色区域出来的，但是为了实际排版需要，第一针就隐藏了火箭，所以在旧版本上，就不会多出红色的区域，新版本就多出来这么一块，而每个龙骨的坐标我都是根据龙骨的高度计算的，这里代码都没变，很费解

**Comment by akdcl** [comment]
已经修复这个问题了，关于二进制的问题，你需要将动画重新导出一下就好了

**Comment by puny-d** [comment]
好的，已经修复了，非常感谢
