### ISSUE TITLE
DragonBonesJS PIXI - Change PIXI.Texture/image of one slot and not whole armature?

### ISSUE THREAD

**Issue by Billydwilliams** [DragonBones/DragonBonesJS#32]
I want to take an image and replace the current on on a specific slot.
Right now the only option i see is to replace the entire texture.

**Comment by akdcl** [comment]
You can set replace slot display like this:
```
slot.display = anyPixiDIsplayObject;
```

Or you can see this [demo](https://github.com/DragonBones/DragonBonesJS/blob/master/Pixi/Demos/src/ReplaceSlotDisplay.ts).

**Comment by Billydwilliams** [comment]
Ok so slot.display = anyPixiDIsplayObject; replaces the image.
But the transform data is incorrect, so it animates weird.
How do i set the transform data for slot.display?

**Comment by akdcl** [comment]
You can set bone.offset to modify slot.display transform.

**Comment by Billydwilliams** [comment]
Looks like the variables I needed to change were on the slot itself.
_pivotX and _pivoitY
