### ISSUE TITLE
很奇怪的问题

### ISSUE THREAD

**Issue by Kehao** [DragonBones/DragonBonesJS#35]
![default](https://user-images.githubusercontent.com/117308/28964351-fb65d47e-793e-11e7-995f-bc77ab81849f.png)
有些浏览器的console.assert使用会有差异，使用dragonBone.js的时候会报TypeError: Type error，
我要手动的改成 DragonBones.assert = console.assert.bind(console)才行,不知道具体的原因。

**Comment by akdcl** [comment]
感谢，已经改为使用控制台断言
