### ISSUE TITLE
tint及其动画在pixi下没有作用？

### ISSUE THREAD

**Issue by harrisyu** [DragonBones/DragonBonesJS#37]
Pixi 版本 4.5.4
在 Dragon Bones Pro 制作的tint和动画， 在pixi中没有效果， 是还没添加这个功能？

**Comment by akdcl** [comment]
对，确实没有实现，pixijs 应该如何实现修改 sprite displayObject mesh 的颜色呢？
https://github.com/DragonBones/DragonBonesJS/blob/master/Pixi/4.x/src/dragonBones/pixi/PixiSlot.ts#L130-L132

**Comment by harrisyu** [comment]
对于mesh可以用tintRgb
http://pixijs.download/release/docs/PIXI.mesh.Mesh.html#tintRgb
对于sprite可以用tint属性:(现阶段rgb需要转hex)
http://pixijs.download/release/docs/PIXI.Sprite.html#tint

已经在chrome控制台亲测可用,如
armatureDisplay.children[6].tintRgb = [0,1,1]
armatureDisplay.children[6].tint = 0xFFFFFF

**Comment by harrisyu** [comment]
好了, 搞定, 不用typescript 只能纯javascript了:
        PixiSlot.prototype._updateColor = function () {
            this._renderDisplay.alpha = this._colorTransform.alphaMultiplier;
            this._renderDisplay.tint = PIXI.utils.rgb2hex([
                this._colorTransform.redMultiplier,
                this._colorTransform.greenMultiplier,
                this._colorTransform.blueMultiplier
            ]);
        };

**Comment by akdcl** [comment]
感谢，我还尽快在 pixi 中实现
