### ISSUE TITLE
InteractionEventType error from PIXI.ArmatureDisplay.ts

### ISSUE THREAD

**Issue by deCompany** [DragonBones/DragonBonesJS#39]
Hi, I'm playing with DragonBonesJS 3.0.1 + PIXI 4.5.3 in VS Code (in typescript).

When I add a click listener to the stage and click my added armatureDisplay nothing happens and the event doesn't shoot. The Code throws two errors:
PixiArmatureDisplay.ts > [ts] 'Argument of type 'string' is not assignable to parameter of type 'InteractionEventTypes'.' (165,30).
PixiArmatureDisplay.ts > [ts] 'Argument of type 'string' is not assignable to parameter of type 'InteractionEventTypes'.' (171,33).

Everything is set up like in HelloDragonBones example - the only difference is different texture and armature data files. The added armatureDisplay is visible on stage and the proper animation is playing.

**Comment by akdcl** [comment]
Hi, the compile error has been fixed.
