### ISSUE TITLE
功能建议：可以添加对phaser的sdk么

### ISSUE THREAD

**Issue by koalaylj** [DragonBones/DragonBonesJS#40]
如果可以的话，希望能添加对phaser支持的SDK。

**Comment by akdcl** [comment]
目前还不支持 phaser，可以尝试使用 egret，不过可以看到，龙骨运行时对接一个引擎并不是十分的复杂，代码量通常只有几百行，你可以试试支持：）

**Comment by koalaylj** [comment]
主要是公司技术栈一直是phaser，看龙骨很好用，就想配合下使用。
我看了下pixi的SDK，不是很复杂。
phaser主要是没有mesh，phaser在集成pixi的时候把mesh给去掉了。
我自己想自己写个对phaser的sdk，但有个地方有点不明白，想请教下：如果想加mesh功能(播放mesh动画)会有很大工作量么？需要了解egret的底层么，mesh所有相关的部分？

**Comment by akdcl** [comment]
如果加 mesh 功能，就需要对 mesh 有了解，但不需要对 egret 有了解，因为 db 的核心逻辑是和渲染引擎无关的，不过你可以借鉴 egret 的 mesh 或 pixi 的 mesh 渲染来尝试，通常渲染 mesh 需要涉及到渲染底层

**Comment by akdcl** [comment]
已经添加了对 phaser 的支持。
