### ISSUE TITLE
BUG: error TS2345

### ISSUE THREAD

**Issue by mobiledevnetwizzy** [DragonBones/DragonBonesJS#42]
I am trying to compile the `head@master` branch, but get these errors:
```
src/dragonBones/pixi/PixiArmatureDisplay.ts(165,30): error TS2345: Argument of type 'string' is not assignable to parameter of type 'InteractionEventTypes'.
src/dragonBones/pixi/PixiArmatureDisplay.ts(171,33): error TS2345: Argument of type 'string' is not assignable to parameter of type 'InteractionEventTypes'.
```
It seems that the docs doesn't define what blob of `pixi.js.d.ts` was used to compile.
I would love to see
 * the dependencies bundled or link in the README to a specific blob (eg, https://github.com/pixijs/pixi-typescript/blob/38f0fec6c682fe865fccc948f3674cf359549caf/pixi.js.d.ts)
* DragonbonesPixi updated to the latest PIXI ;)

**Comment by akdcl** [comment]
Hi, the compile error has been fixed.
But there is a greater discrepancy between the declaration and the implementation in  pixi.js.d.ts and pixi.js

**Comment by mobiledevnetwizzy** [comment]
Thanks, compiling now without errors/warnings!
