### ISSUE TITLE
Compilation errors from the latest update (PIXI)

### ISSUE THREAD

**Issue by deCompany** [DragonBones/DragonBonesJS#46]
Hi and thanks for the cool update! 
Here are some errors I get on compilation (VSCode) with PIXI project (causes crashing in browser):

PixiArmatureDisplay.ts
-Class "PixiArmatureDisplay" incorrectly implements interface "IArmatureProxy"- (27, 18)

PixiFactory.ts
-Argument of type "PixiArmatureDisplay" is not assignable to parameter of type "IEventDispatcher"- (43, 57)
-Argument of type "PixiArmatureDisplay" is not assignable to parameter of type "IArmatureProxy"- (99, 17)
-Type "IEventDispatcher" cannot be converted to type "PixiArmatureDisplay"- (194, 20)
-Property "clock" does not exist on type "PixiFactory"- (208, 40)
 
PixiSlot.ts
-Property "_armatureData" does not exist on type "Armature". Did you mean "armatureData"?- (243, 95)
-Property "_armatureData" does not exist on type "Armature". Did you mean "armatureData"?- (273, 42)

**Comment by deCompany** [comment]
Update.
I am sorry if this is me doing something wrong. I get all this errors when I use "out" files from DragonBones folder. I've found there are files with the same names in every target folder too (Pixi, Phaser, etc) - so maybe I should use these files.

If I use files from "Pixi/4.x/out" folder I get a bunch of errors like
PixiArmatureDisplay.ts
-Duplicate identifier "PixiArmatureDisplay"-
and dragonBones.d.ts
--Duplicate identifier "PixiArmatureDisplay"-

At least these errors don't cause crashes. Hope this helps )

**Comment by akdcl** [comment]
Hi, you should use files from `pixi/4.x/out`.
Duplicate identifier error, may be you imports duplicate dragonbones declaration file?

**Comment by deCompany** [comment]
Now that's clear, thanks.
As for duplicated import - I don't import it with code. I just have one file in tsDefinitions folder, one file in js folder and Pixi... files in source folder. It worked well until the latest update.
I forgot to mention: all the duplicate errors are from Pixi... files (PixiFactory, PixiSlot, PixiArmatureDisplay, PixiTextureAtlasData, PixiTextureData).

**Comment by deCompany** [comment]
I'm sorry, it was completely my fault. I had dragonBones  source .ts files in my project folders. That was the reason for duplication error. Thanks for your time. )
