### ISSUE TITLE
疑问：phaser目录下2.x 3.x是什么意思？

### ISSUE THREAD

**Issue by koalaylj** [DragonBones/DragonBonesJS#47]
疑问：phaser目录下2.x 3.x目录是什么意思？区别是什么？

**Comment by akdcl** [comment]
2.x 对应的是 phaser 的社区版
3.x 对应的是 phaser 的正式版（3.x 还没有发布）

因为 phaser 3.x 还在 beta 阶段，所以暂时没有对接

**Comment by koalaylj** [comment]
明白了，多谢回答。
项目需要协作开发者么，我这边对phaser2.x源码比较熟悉，phaserSDK相关的东西我可以帮忙维护。
我的邮箱：koalaylj@gmail.com.

**Comment by akdcl** [comment]
@koalaylj 那真是太好了：）
