### ISSUE TITLE
[bug] small element in preview box order

### ISSUE THREAD

**Issue by djmisterjon** [DragonBones/DragonBonesJS#51]
hi i have a strange bug in the draw order?
ex:step
1: put a object under object.
2: save project
3: move object again
4: bug it showed hover object

if i save project, and move the object , it will draw render over again the body object ????
i made a video to show you the bugs
https://youtu.be/2kQ0rxA7iSA

am new on dragonBone, so if am doing mistake thank to tell me.
thank a lot for help me understand this bug and what am do bad.

EDIT:
I notice that it seems to happen with small element only, how fix this ?
EDIT:2
after some test, it not affect export, and the test preview in file> preview.
Only bug in preview sofware box.
I wonder if this is not a problem of harware, I have a gtx 1070.
Someone else has this problem. ?
This bug make animation very hard.
i try edit my gpu config , but this not solved the issue.
I do not know the source code of the software, but I think there is a problem when an object contains less than 250 pixel for rendering preview order in box.

**Comment by doubleclip** [comment]
This is a draw order issue. We will fix it. Thank you for your feedback ~
