### ISSUE TITLE
[Error] Phaser childs not working when dragonbones.js is included.

### ISSUE THREAD

**Issue by Llop1s** [DragonBones/DragonBonesJS#58]
Hi!

I have a game where I'm using sprites with other sprites as children and when I include the dragonbones.js in my project all the children sprites go to position 0,0 and loses all parent properties.

Can you help me? Thanks!

**Comment by Jorgegarve** [comment]
Try to change all your Phaser.Image to Phaser.Sprite. This should fix it. :)

**Comment by Llop1s** [comment]
Thank you bro!
