### ISSUE TITLE
怎么求2d精灵的宽高

### ISSUE THREAD

**Issue by shijunti19** [DragonBones/DragonBonesJS#74]
我查了半天好像width和height都是缩放比例，我是0.2
怎么求在场景中的实际高度，像素，我想做物理碰撞用

**Comment by cpet** [comment]
If you're using Phaser 2 or 3 I remember you can get the container width and height using the getBounds() method on container.
Google Translator:
如果您使用的是Phaser 2或3，我记得您可以使用容器上的getBounds（）方法获得容器的宽度和高度。

**Comment by jcyuan** [comment]
请使用getBounds()
