### ISSUE TITLE
编译代码出错

### ISSUE THREAD

**Issue by xuanjinliang** [DragonBones/DragonBonesJS#82]
执行代码： dbr pixijs@4.8.3
build_pixi.js
![qq20181230-171410](https://user-images.githubusercontent.com/8176702/50545774-6a33a100-0c56-11e9-9082-0f848d8d93b4.png)

`path.join(this.cacheFolder, `pixi-typescript-${ this.version }/pixi.js.d.ts`)`

**Comment by wujohns** [comment]
这个应该是当时写时候的疏忽，老哥如果方便的话提下pr解决下吧：）（合并后会检查相应的编译没有问题，我们这边会发布新的version的npm包）
本地如果急着用的话，可以下该工程后修复此bug后，直接npm install -g <工程路径>手动替换这个包，然后做相应的编译工作

**Comment by wujohns** [comment]
@xuanjinliang 刚刚是我的疏忽，这个提交需要提交到dev分支（等待之后的合并），master的那个广告revert了（之后会做一次rebase还原到提交前的状态），方便的话你那边再提交一次到dev分支吧。。。。我的锅
